<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>
<center><b><h1>Preet Parmar(211)</b></center>    
<center><b><h1>Lab - 2</b></center>    
<pre>

# Exploratory Data Analysis (EDA) Of Loan Default detection

In [4]:
import pandas as pd
df = pd.read_csv("Loan_default.csv")
df

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,8C6S86ESGC,19,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255343,98R4KDHNND,32,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1
255344,XQK1UUUNGP,56,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0
255345,JAO28CPL4H,42,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,Yes,Yes,Other,No,0
255346,ZTH91CGL0B,62,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

# 1. Dataset Overview

Dataset Overview is the first step in **Exploratory Data Analysis (EDA)**. It provides a quick understanding of the dataset's structure, size, and features before performing further analysis.

### Questions

1. What is the shape of the dataset?
2. How many rows are there?
3. How many columns are there?
4. What is the data type of each column?
5. Print the name of all the columns.

In [5]:
df.shape

(255347, 18)

In [6]:
df.shape[0]

255347

In [7]:
df.shape[1]

18

In [8]:
df.dtypes

LoanID             object
Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education          object
EmploymentType     object
MaritalStatus      object
HasMortgage        object
HasDependents      object
LoanPurpose        object
HasCoSigner        object
Default             int64
dtype: object

In [11]:
df.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Default'],
      dtype='object')

# 2. DataFrame Summary

A **DataFrame Summary** provides a statistical overview of the dataset. It helps you quickly understand the distribution, central tendency, spread, and count of values in numerical columns. You can summarize the entire DataFrame or focus on specific columns based on your analysis needs.

### Questions

1. Summarize the entire DataFrame.
2. Summarize all the columns.
3. Summarize any one particular column.
4. Summarize any two or more columns at once.

In [12]:
df.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

In [13]:
df.describe(include="all")

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
count,255347,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347,255347,255347,255347,255347,255347,255347,255347.000000
unique,255347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,3,2,2,5,2,NaN
top,I38PQUQS96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bachelor's,Part-time,Married,Yes,Yes,Business,Yes,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64366,64161,85302,127677,127742,51298,127701,NaN
mean,NaN,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.116128
std,NaN,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.320379
min,NaN,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,NaN,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
75%,NaN,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
max,NaN,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000

In [14]:
df["LoanAmount"].describe()

count    255347.000000
mean     127578.865512
std       70840.706142
min        5000.000000
25%       66156.000000
50%      127556.000000
75%      188985.000000
max      249999.000000
Name: LoanAmount, dtype: float64

In [18]:
df[["LoanAmount" , "CreditScore" , "Default"]].describe(include="all")

          LoanAmount    CreditScore        Default
count  255347.000000  255347.000000  255347.000000
mean   127578.865512     574.264346       0.116128
std     70840.706142     158.903867       0.320379
min      5000.000000     300.000000       0.000000
25%     66156.000000     437.000000       0.000000
50%    127556.000000     574.000000       0.000000
75%    188985.000000     712.000000       0.000000
max    249999.000000     849.000000       1.000000

# 3. Selecting Columns

Selecting columns allows you to extract one or more specific columns from a DataFrame for analysis. This helps you focus only on the relevant data instead of working with the entire dataset.

### Questions

1. Select and display the **`LoanAmount`** column.
2. Select and display the **`Education`**, **`InterestRate`**, and **`Default`** columns.
3. Select the **`Income`**, **`LoanAmount`**, and **`CreditScore`** columns, and display only the **last 10 records**.
4. Store the **`InterestRate`** column as a Pandas **Series** named **`IR`**, and print its data type.

In [24]:
df["LoanAmount"]

0          50587
1         124440
2         129188
3          44799
4           9139
           ...
255342    210682
255343    189899
255344    208294
255345     60575
255346     18481
Name: LoanAmount, Length: 255347, dtype: int64

In [26]:
df[["Education" , "InterestRate" , "Default"]]

          Education  InterestRate  Default
0        Bachelor's         15.23        0
1          Master's          4.81        0
2          Master's         21.17        1
3       High School          7.07        0
4        Bachelor's          6.51        0
...             ...           ...      ...
255342   Bachelor's         14.11        0
255343  High School         11.55        1
255344  High School          5.29        0
255345  High School         20.90        0
255346   Bachelor's          6.73        0

[255347 rows x 3 columns]

In [28]:
df[["Income" , "LoanAmount" , "CreditScore"]].tail(10)

        Income  LoanAmount  CreditScore
255337   73743      140354          300
255338   21711      168231          352
255339   69492      122962          348
255340   61809      119238          444
255341  129890      116119          701
255342   37979      210682          541
255343   51953      189899          511
255344   84820      208294          597
255345   85109       60575          809
255346   22418       18481          636

# 4. Filtering Data

Filtering allows you to retrieve only the rows that satisfy one or more conditions. It helps you focus on specific records for analysis without modifying the original dataset.

### Questions

1. Display all records where the **`CreditScore`** is less than **400**.

2. Display all records where the **`LoanAmount`** is greater than **200000**.

3. Display all records where the **`EmploymentType`** is **'Unemployed'**.

4. Display all records where the **`DTIRatio`** is greater than **0.50** and the **`Default`** value is **1**.

5. Identify the **high-risk borrower segment** by filtering records that satisfy all of the following conditions:

   - `CreditScore` less than **650**
   - `Income` less than **50000**
   - `DTIRatio` greater than **0.40**
   - `InterestRate` greater than **12**
   - `MonthsEmployed` less than **24**

In [33]:
df[df["CreditScore"] < 400]

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
11,Y8UETC3LSG,28,149227,139759,375,56,3,5.84,36,0.80,PhD,Full-time,Divorced,No,No,Education,Yes,1
13,GX5YQOGROM,53,117550,95744,395,112,4,3.58,24,0.73,High School,Unemployed,Single,No,No,Auto,Yes,0
16,ZDDRGVTEXS,20,119704,25697,313,49,1,9.63,24,0.28,PhD,Unemployed,Single,Yes,No,Home,No,0
18,O1IKKLC69B,19,40718,78515,319,119,2,14.00,24,0.17,Bachelor's,Self-employed,Divorced,Yes,No,Education,No,1
19,F7487UU2BF,41,123419,161146,376,65,4,16.96,60,0.39,High School,Self-employed,Single,Yes,No,Other,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255317,UA896W9ZCS,46,49616,31272,372,31,4,23.06,12,0.13,Master's,Part-time,Divorced,Yes,Yes,Education,No,0
255324,Q8OXUYF0TI,50,34641,108855,347,17,4,11.77,24,0.47,PhD,Unemployed,Divorced,Yes,No,Business,No,1
255337,DSL4O0KAWD,64,73743,140354,300,0,2,4.12,12,0.24,PhD,Self-employed,Single,Yes,No,Education,Yes,0
255338,6V8S5IUS63,68,21711,168231,352,78,2,9.71,60,0.36,PhD,Full-time,Divorced,Yes,Yes,Home,No,0
255339,O6SWO6CBGB,51,69492,122962,348,66,2,10.83,48,0.27,High School,Part-time,Divorced,No,No,Home,No,0

In [40]:
df[df["LoanAmount"] > 200000]

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
9,CM9L1GTT2P,40,132784,228510,480,114,4,9.09,48,0.33,High School,Self-employed,Married,Yes,No,Other,Yes,0
15,O5DM5MPPNA,41,74064,230883,432,31,2,5.00,60,0.89,Master's,Unemployed,Married,Yes,No,Auto,No,0
31,P3EX8G0AYT,44,100284,225403,551,31,1,18.77,36,0.17,Master's,Unemployed,Divorced,No,Yes,Business,Yes,1
36,8NTWNU4HTY,64,102463,218433,506,24,2,9.23,60,0.86,Master's,Unemployed,Married,No,No,Auto,Yes,0
42,KAC7P2RE1X,68,111716,215851,747,99,3,18.84,60,0.40,High School,Unemployed,Divorced,No,Yes,Home,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255326,FYGOB527WK,48,44894,202276,473,10,3,7.32,48,0.26,High School,Unemployed,Single,No,Yes,Auto,No,0
255328,P3UCIPJVTB,50,21890,226684,839,62,1,5.80,48,0.65,High School,Self-employed,Divorced,Yes,No,Home,No,0
255335,OQ99DN6JL4,41,124446,249800,650,60,4,3.32,24,0.21,High School,Unemployed,Single,Yes,No,Other,No,0
255342,8C6S86ESGC,19,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255344,XQK1UUUNGP,56,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0

In [41]:
df[df["EmploymentType"] == "Unemployed"]

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
5,A9S62RQ7US,25,90298,90448,720,18,2,22.72,24,0.10,High School,Unemployed,Single,Yes,No,Business,Yes,1
6,H8GXPAOS71,38,111188,177025,429,80,1,19.11,12,0.16,Bachelor's,Unemployed,Single,Yes,No,Home,Yes,0
10,IA35XVH6ZO,28,140466,163781,652,94,2,9.08,48,0.23,High School,Unemployed,Married,No,No,Education,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255326,FYGOB527WK,48,44894,202276,473,10,3,7.32,48,0.26,High School,Unemployed,Single,No,Yes,Auto,No,0
255329,QXBHNXNA9X,34,53658,187245,847,35,3,3.08,48,0.85,High School,Unemployed,Single,Yes,Yes,Auto,Yes,0
255333,BM4B25R7EI,22,45575,43355,545,99,1,21.86,12,0.52,PhD,Unemployed,Married,Yes,Yes,Education,No,1
255335,OQ99DN6JL4,41,124446,249800,650,60,4,3.32,24,0.21,High School,Unemployed,Single,Yes,No,Other,No,0
255346,ZTH91CGL0B,62,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

In [43]:
df[(df["DTIRatio"] == 0.50) & (df["Default"] == 1)]

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
280,UZUW6Q652D,45,146321,148088,304,106,2,18.69,24,0.5,PhD,Part-time,Married,Yes,No,Education,No,1
651,62UIBIHXWI,22,134935,132709,344,14,3,4.63,24,0.5,PhD,Unemployed,Married,Yes,No,Auto,No,1
1298,RMIDP4M6KH,18,137855,65904,683,17,2,23.18,48,0.5,PhD,Self-employed,Divorced,Yes,Yes,Auto,No,1
1998,8R83M3QJDF,24,99944,45213,655,96,2,16.28,36,0.5,Bachelor's,Unemployed,Married,No,No,Business,No,1
2877,5FB5M1D599,46,45718,61799,431,17,2,22.43,12,0.5,High School,Unemployed,Married,Yes,No,Auto,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251670,6CA62BXMAE,24,32775,54145,594,100,3,22.46,60,0.5,Bachelor's,Part-time,Single,Yes,No,Home,Yes,1
253392,LH016N48MW,52,67660,57354,704,33,4,24.68,48,0.5,High School,Self-employed,Single,No,No,Business,No,1
254281,HO7ZNL86DX,54,67281,135981,726,38,3,4.74,36,0.5,Bachelor's,Part-time,Married,No,No,Auto,Yes,1
254493,0QN6SK79QA,18,100512,7875,756,25,3,20.21,48,0.5,Master's,Full-time,Married,Yes,Yes,Education,No,1
255202,Y4JV3HO365,50,147037,99510,743,48,2,15.81,48,0.5,High School,Unemployed,Divorced,No,No,Business,Yes,1

In [44]:
df[(df["CreditScore"] < 500) & (df["Income"] < 50000) & (df["DTIRatio"] > 0.40) & (df["InterestRate"] > 12) & (df["MonthsEmployed"] < 24)]

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
55,QHPWTGMTU8,37,37173,234059,455,20,3,15.12,48,0.74,PhD,Full-time,Married,No,Yes,Other,No,0
83,QTEXRYSK63,32,46238,134941,421,1,1,12.32,24,0.50,High School,Part-time,Divorced,No,No,Auto,No,0
277,QNWQWY4A8L,57,23764,78444,315,21,2,24.61,36,0.56,Bachelor's,Part-time,Single,Yes,No,Auto,Yes,0
394,RBGYQW2ZUP,50,33014,118574,344,2,1,19.84,12,0.84,Master's,Full-time,Single,Yes,No,Business,No,0
402,NR7X7N3A1C,63,38176,52978,370,2,3,15.49,60,0.84,Bachelor's,Self-employed,Single,Yes,No,Business,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253598,B3OYYVTM7G,55,17385,155324,400,17,3,12.96,36,0.44,Master's,Unemployed,Single,Yes,No,Business,Yes,0
253891,TFABKCW3Y4,61,42189,138135,378,5,1,20.50,48,0.79,Bachelor's,Unemployed,Married,Yes,No,Education,Yes,0
253968,4ZG3RLB1V5,57,32599,91929,373,2,4,18.36,48,0.77,PhD,Part-time,Single,Yes,Yes,Business,No,1
254251,77FCMD364I,21,26646,55849,478,13,2,21.44,48,0.54,Bachelor's,Unemployed,Married,No,No,Home,Yes,0
254940,KN7YOLJMVJ,33,20208,168159,333,17,4,18.05,12,0.69,Master's,Part-time,Divorced,No,No,Education,Yes,1

# 5. Sorting Data

Sorting arranges the rows of a DataFrame in ascending or descending order based on one or more columns. It helps identify the highest, lowest, or ordered values in the dataset.

### Questions

1. Sort the dataset by **`LoanAmount`** in **descending order** and display the top **10** borrowers with the highest loan amounts.

2. Sort the dataset by **`CreditScore`** in **ascending order** and display the first **15** records.

3. Sort the dataset by **`InterestRate`** in **descending order** and display the top **20** borrowers paying the highest interest rates.

4. Sort the dataset first by **`Default`** (descending) and then by **`CreditScore`** (ascending). Display the first **10** records.

5. Identify the **highest-risk borrowers** by combining **filtering, selection, and sorting**:

   - Filter records where:
     - `CreditScore` < 650
     - `DTIRatio` > 0.40
     - `Default` = 1

   - Select only the following columns:
     - `LoanID`
     - `CreditScore`
     - `Income`
     - `LoanAmount`
     - `InterestRate`
     - `DTIRatio`
     - `Default`

   - Sort the resulting data by:
     1. `InterestRate` (descending)
     2. `LoanAmount` (descending)

   - Display the top **15** records and write **3 observations** about the borrowers with the highest risk profile.

In [47]:
df.sort_values("LoanAmount" , ascending=False).head(10)

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
20256,BZ6O5YSSA8,37,114264,249999,598,106,3,8.47,36,0.71,High School,Full-time,Single,Yes,No,Business,Yes,0
232552,TGYZ4AXW7H,52,140430,249998,484,80,4,13.67,24,0.76,PhD,Full-time,Single,Yes,Yes,Education,Yes,0
206804,VIS6H9YBJM,44,76674,249997,304,87,1,12.12,48,0.34,Bachelor's,Full-time,Married,No,No,Other,Yes,0
239262,7OV9HHSV62,26,137747,249996,451,47,4,22.04,36,0.72,PhD,Full-time,Married,Yes,Yes,Home,No,0
135381,RXGEJP7QPL,65,23329,249993,684,4,1,9.35,12,0.47,High School,Self-employed,Divorced,No,Yes,Business,Yes,1
171401,INBGJEMBW3,54,145587,249993,332,59,1,10.70,24,0.44,PhD,Full-time,Divorced,Yes,Yes,Business,Yes,0
32834,T81D0AKB24,64,66167,249992,794,33,2,19.04,12,0.39,High School,Full-time,Single,Yes,No,Other,No,1
182365,TE1MRP009B,37,136184,249990,675,86,2,19.54,48,0.40,Master's,Unemployed,Married,No,Yes,Business,Yes,0
234220,PVLUX5GH5X,18,20288,249989,302,92,2,20.24,60,0.32,PhD,Full-time,Single,No,Yes,Business,No,1
204609,OFQMCX2Z37,39,40994,249988,827,95,1,6.49,12,0.50,High School,Unemployed,Divorced,Yes,Yes,Auto,No,1

In [50]:
df.sort_values("CreditScore" , ascending=True).head(15)

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
159951,NLJLI00NIJ,38,117688,19952,300,27,1,14.11,60,0.51,Bachelor's,Unemployed,Married,No,Yes,Business,No,1
209976,JBL7TU9ODS,47,31962,66533,300,101,3,14.82,60,0.64,Master's,Unemployed,Single,No,No,Business,Yes,0
125243,JHHEW0HYC7,24,53586,79798,300,86,2,5.00,36,0.21,Master's,Self-employed,Married,Yes,Yes,Auto,No,0
200003,U5MJ71Z7U7,35,33830,99614,300,5,1,4.82,24,0.29,PhD,Full-time,Married,Yes,No,Other,No,0
113980,2Y340RE0Y2,27,48728,221478,300,47,2,22.91,48,0.14,PhD,Self-employed,Divorced,No,No,Auto,No,1
104936,4L7NX50RVS,22,127513,246432,300,31,4,6.61,12,0.75,PhD,Self-employed,Married,No,No,Auto,No,1
178926,BO9EVOX5IX,36,61352,149465,300,35,1,18.14,24,0.33,PhD,Unemployed,Married,No,Yes,Auto,Yes,0
105819,O5SUBTA9I8,40,126490,234038,300,99,4,5.87,24,0.69,PhD,Part-time,Single,No,Yes,Other,No,0
218144,2LOZOBVKR0,50,39700,108847,300,118,2,15.32,36,0.26,PhD,Part-time,Divorced,Yes,Yes,Education,Yes,0
138645,634DT1FZBY,66,55170,205584,300,68,4,7.78,12,0.32,Master's,Part-time,Married,No,No,Auto,Yes,0
125177,U8V2Q7REI0,53,49528,146916,300,119,3,17.76,48,0.32,Bachelor's,Unemployed,Married,No,No,Business,Yes,0
75319,JJFUYCZYR3,61,101179,36599,300,112,1,22.51,48,0.39,PhD,Self-employed,Divorced,Yes,Yes,Education,No,0
178095,VVA2SD78RW,33,104324,238553,300,72,2,8.57,48,0.13,Master's,Part-time,Married,Yes,Yes,Home,No,1
66555,3DLKJTD58N,50,70979,156794,300,112,3,5.59,12,0.75,Master's,Unemployed,Divorced,Yes,Yes,Other,No,0
254794,8K5LR39AHQ,60,128474,226768,300,57,4,2.37,24,0.15,Master's,Self-employed,Married,No,Yes,Business,Yes,0

In [51]:
df.sort_values("InterestRate" , ascending=False).head(20)

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
139618,IZR3HH9EGO,60,115446,65370,335,51,4,25.0,60,0.46,PhD,Full-time,Single,No,No,Auto,Yes,0
15166,BHYZBBTTVN,68,83030,92174,398,95,1,25.0,12,0.89,Bachelor's,Self-employed,Married,No,Yes,Business,Yes,0
219887,QFWRQD2FJV,18,70063,125793,639,39,4,25.0,24,0.44,PhD,Part-time,Married,No,No,Other,No,1
53301,BDUC5NF515,55,110674,137638,810,25,1,25.0,60,0.38,High School,Unemployed,Single,Yes,Yes,Home,Yes,0
76511,DPW2MKCOYH,34,74245,87235,803,39,1,25.0,12,0.75,Bachelor's,Full-time,Single,Yes,No,Education,Yes,0
88852,I5RHWFFR30,49,100763,79163,821,75,3,25.0,60,0.17,PhD,Self-employed,Married,Yes,No,Business,No,0
177944,JXEFL5UJ22,68,47375,38484,323,30,2,25.0,12,0.60,High School,Self-employed,Divorced,Yes,Yes,Business,No,0
81539,YRYS6J1ULV,63,108158,116889,352,38,4,25.0,60,0.35,PhD,Full-time,Divorced,No,No,Home,No,1
160486,ZDBFTPNGS7,64,136615,12418,666,69,3,25.0,24,0.28,High School,Unemployed,Single,Yes,No,Education,Yes,0
187625,O8M2TK1N4J,69,67995,140313,527,0,1,25.0,36,0.37,PhD,Self-employed,Single,Yes,Yes,Business,No,0
117264,SEPV2SFJ5E,30,82869,205910,702,7,1,25.0,36,0.76,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,1
26568,D0O9MHEOQI,60,38367,67952,805,70,3,25.0,12,0.33,High School,Unemployed,Married,Yes,Yes,Auto,No,0
213207,WWOL22D5HL,42,17080,9065,434,103,2,25.0,36,0.23,PhD,Self-employed,Single,No,No,Other,Yes,0
6472,ENT020CSGD,37,124784,193423,697,27,2,25.0,60,0.42,Master's,Part-time,Divorced,No,Yes,Auto,Yes,0
238812,0MAO214GZU,65,104122,152496,474,114,1,25.0,36,0.73,Master's,Part-time,Divorced,No,Yes,Education,No,0
79994,2KEK7ACV34,64,124334,197142,323,44,2,25.0,48,0.56,High School,Full-time,Divorced,Yes,Yes,Home,No,1
120067,S5M2YCMWTW,35,147015,13821,770,102,3,25.0,60,0.66,Master's,Unemployed,Married,No,No,Education,Yes,0
154395,V1YRI0I8DW,29,121867,153769,594,82,2,25.0,60,0.64,PhD,Part-time,Divorced,Yes,No,Business,Yes,0
69936,1ZUDBOXQAA,41,23270,78928,723,11,4,25.0,12,0.52,PhD,Full-time,Divorced,No,Yes,Education,Yes,0
216463,0VJXJKVMJE,19,92423,204852,789,86,1,25.0,36,0.29,Bachelor's,Unemployed,Divorced,Yes,Yes,Other,No,0

In [52]:
df.sort_values(["Default" , "CreditScore"] , ascending=[False , True]).head(10)

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
2561,CIS1M4Q4DN,20,118332,211028,300,6,3,15.46,36,0.74,High School,Part-time,Single,No,No,Education,Yes,1
2576,X507HBUSXL,56,25442,118892,300,7,4,22.63,60,0.67,Master's,Full-time,Married,No,No,Other,Yes,1
3547,SWEO9RN44J,44,76912,132882,300,80,1,20.21,60,0.33,Master's,Unemployed,Married,No,Yes,Other,Yes,1
5597,Q057CQ65UF,60,83205,245621,300,15,1,24.52,36,0.27,Bachelor's,Part-time,Divorced,No,No,Business,No,1
8304,3SBMA7KAYV,18,74378,27637,300,37,2,16.11,36,0.22,High School,Unemployed,Married,No,No,Auto,Yes,1
20972,J0IY4N83S7,64,95649,78635,300,97,4,23.04,24,0.58,Master's,Full-time,Divorced,No,No,Business,No,1
21449,IEXC94MQKJ,57,100322,151862,300,114,1,16.15,48,0.39,High School,Unemployed,Divorced,Yes,Yes,Business,No,1
27060,DGIF4BGB8R,35,18803,98771,300,23,1,12.61,60,0.48,PhD,Part-time,Divorced,No,Yes,Home,Yes,1
33538,9ZE53DHWDA,59,96499,164969,300,61,2,16.75,12,0.86,PhD,Unemployed,Married,No,No,Other,Yes,1
36120,26ZT9WMCZI,50,98305,240142,300,58,4,24.39,60,0.67,High School,Part-time,Married,No,No,Business,No,1

In [57]:
xyz = df[(df["CreditScore"] < 650) & (df["DTIRatio"] > 0.40) & (df["Default"] == 1)]

xyz[["LoanID" , "CreditScore" , "Income" , "LoanAmount" , "InterestRate" , "DTIRatio" , "Default"]].sort_values(["InterestRate" , "LoanAmount"] , ascending=[False , False]).head(15)

,LoanID,CreditScore,Income,LoanAmount,InterestRate,DTIRatio,Default
79994,2KEK7ACV34,323,124334,197142,25.00,0.56,1
46593,7EN8YA37EO,404,28744,179265,25.00,0.51,1
29291,SSMTMEB9V9,359,28667,170341,25.00,0.86,1
219887,QFWRQD2FJV,639,70063,125793,25.00,0.44,1
79519,CLSZWLGGGN,360,83904,64580,25.00,0.65,1
210369,KDJCKP7CA2,636,142049,246571,24.99,0.77,1
68807,N2X49FKIHC,623,15361,244665,24.99,0.65,1
40779,DKY1MNQ84A,440,91796,233570,24.99,0.86,1
154439,EN5UKPIQC4,489,16534,221024,24.99,0.53,1
23674,CTDHC8Z5PX,535,35383,215920,24.99,0.52,1
127129,60DSFI44OU,310,64947,191686,24.99,0.60,1
139814,PX59W5RBDQ,490,76982,169217,24.99,0.43,1
150282,YPMNSW4OJV,356,46735,150575,24.99,0.73,1
181716,6YFUEA2KUP,388,50849,139849,24.99,0.45,1
90453,HWVHQ1PS4R,409,122384,133302,24.99,0.43,1

# 6. Value Counts

Value Counts helps determine the frequency of unique values in a column. It is useful for understanding class distribution, identifying dominant categories, and detecting imbalance in the dataset.

### Questions

1. Count how many borrowers belong to each **`EmploymentType`**.

2. Count how many loans were taken for each **`LoanPurpose`**.

3. Count the number of borrowers in each **`Education`** category and display the results in descending order.

In [59]:
df["EmploymentType"].value_counts()

EmploymentType
Part-time        64161
Unemployed       63824
Self-employed    63706
Full-time        63656
Name: count, dtype: int64

In [60]:
df["LoanPurpose"].value_counts()

LoanPurpose
Business     51298
Home         51286
Education    51005
Other        50914
Auto         50844
Name: count, dtype: int64

In [61]:
df["Education"].value_counts().sort_values()

Education
PhD            63537
Master's       63541
High School    63903
Bachelor's     64366
Name: count, dtype: int64

# 7. Null Value Analysis

Null Value Analysis helps identify missing data in a dataset. Detecting and handling missing values is an important preprocessing step before performing data analysis or building machine learning models.

### Questions

1. Display the total number of missing values in each column of the dataset.

2. Display only the columns that contain one or more missing values.

3. Calculate the percentage of missing values for each column and sort the results in descending order.

In [62]:
df.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [63]:
missing_cols = df.columns[df.isnull().any()]
print(missing_cols)

Index([], dtype='object')

In [64]:
df.isnull().mean() * 100

LoanID            0.0
Age               0.0
Income            0.0
LoanAmount        0.0
CreditScore       0.0
MonthsEmployed    0.0
NumCreditLines    0.0
InterestRate      0.0
LoanTerm          0.0
DTIRatio          0.0
Education         0.0
EmploymentType    0.0
MaritalStatus     0.0
HasMortgage       0.0
HasDependents     0.0
LoanPurpose       0.0
HasCoSigner       0.0
Default           0.0
dtype: float64